export const STUDENTS_REQUEST = 'STUDENTS_REQUEST'
export const STUDENTS_SUCCESS = 'STUDENTS_SUCCESS'
export const STUDENTS_FALIURE = 'STUDENTS_FALIURE'

export const STUDENTS_SEARCH_REQUEST = 'STUDENTS_SEARCH_REQUEST'
export const STUDENTS_SEARCH_SUCCESS = 'STUDENTS_SEARCH_SUCCESS'
export const STUDENTS_SEARCH_FALIURE = 'STUDENTS_SEARCH_FALIURE'


export const SCHOOL_DETAILS_REQUEST = 'SCHOOL_DETAILS_REQUEST'
export const SCHOOL_DETAILS_SUCCESS = 'SCHOOL_DETAILS_SUCCESS'
export const SCHOOL_DETAILS_FALIURE = 'SCHOOL_DETAILS_FALIURE'