export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST'
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS'
export const TRANSACTION_FALIURE = 'TRANSACTION_FALIURE'


export const TRANSACTION_STUDENT_REQUEST = 'TRANSACTION_STUDENT_REQUEST'
export const TRANSACTION_STUDENT_SUCCESS = 'TRANSACTION_STUDENT_SUCCESS'
export const TRANSACTION_STUDENT_FALIURE = 'TRANSACTION_STUDENT_FALIURE'