export const GRADE_REQUEST = 'GRADE_REQUEST'
export const GRADE_SUCCESS = 'GRADE_SUCCESS'
export const GRADE_FALIURE = 'GRADE_FALIURE'

export const ADD_GRADE_REQUEST = 'ADD_GRADE_REQUEST'
export const ADD_GRADE_SUCCESS = 'ADD_GRADE_SUCCESS'
export const ADD_GRADE_FALIURE = 'ADD_GRADE_FALIURE'

export const UPDATE_GRADE_REQUEST = 'UPDATE_GRADE_REQUEST'
export const UPDATE_GRADE_SUCCESS = 'UPDATE_GRADE_SUCCESS'
export const UPDATE_GRADE_FALIURE = 'UPDATE_GRADE_FALIURE'

export const DELETE_GRADE_REQUEST = 'DELETE_GRADE_REQUEST'
export const DELETE_GRADE_SUCCESS = 'DELETE_GRADE_SUCCESS'
export const DELETE_GRADE_FALIURE = 'DELETE_GRADE_FALIURE'