export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FALIURE'
export const TRANSFER_DATA = 'TRANSFER_DATA'


export const PASSWORD_FORGET_REQUEST = 'PASSWORD_FORGET_REQUEST'
export const PASSWORD_FORGET_SUCCESS = 'PASSWORD_FORGET_SUCCESS'
export const PASSWORD_FORGET_FAILURE = 'PASSWORD_FORGET_FALIURE'