export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST'
export const DEPOSIT_SUCCESS = 'DEPOSIT_SUCCESS'
export const DEPOSIT_FALIURE = 'DEPOSIT_FALIURE'

export const KEY_REQUEST = 'KEY_REQUEST'
export const KEY_SUCCESS = 'KEY_SUCCESS'
export const KEY_FALIURE = 'KEY_FALIURE'
export const DEPOSIT_REQUEST_DATA = 'DEPOSIT_REQUEST_DATA'
